### ISSUE TITLE
Small quality-of-life enhancements

### ISSUE THREAD

**Issue by Benji377** [tfobz/carbon-calculator#34]
# Enhancements

## Code related:
1. Change the title into _CF Train in VET - Carbon Footprint Calculator_.
2. Add a helping text on blank pages to describe what a user should do next and why. Example:
![Screenshot 2022-11-24 112217](https://user-images.githubusercontent.com/50681275/203760170-83fb4c9c-df92-4e35-81fe-8cd4423443ad.png)
3. Add a landing page, with a simple description of the project and its purpose.
4. Labels: Name -> _Organisation's Name_, Factors -> _Country_
5. When adding emissions, if there is currently no emission, instead of displaying a blank plage, one could directly display the list of possible modules that appears when you click on the "+" button anyway.
6. Labels: Add -> _Add emission factor_ , km -> _driven km a year_, Gläser -> _Gläser pro Jahr_
7. Logo: change it into the logo "CF Train in VET"
8. Instead of the top three dots on the upper right corner, write "= Menu"
9. The icon of the website does nothing when clicking, maybe add a link to the main page for easier and intuitive navigation
10. Link to the project website
12. Add a small description to each emissions' module to explain why the measurement was made in kg, for example, or how the value should be inserted to match the calculated one.
13. Show the countries beside the organisation names e.g. **_"TFO Max Valier"_** (_Italy_)

## GitHub related:
1. automatically label issues and pull-requests, depending on the chosen template
2. create a [project board](https://github.com/tfobz/carbon-calculator/projects) which displays current status of the app and next steps

**Comment by Benji377** [comment]
Point 2 and 6 of the coding part, only truly make sense if this project gets considered as a standalone

**Comment by Chris3444** [comment]
Points 3,4,5,6,7,8,9 and 12 done

**Comment by mwallnoefer** [comment]
Left ToDo:

1. All labels of the third level (e.g. "TFO BZ" as organisation) need to be increased in size and aligned better (center) 
2. On the _homeland page_ (screen _"Add organisation"_): text "click + to add new organisation" needs to be increased in size and aligned across the screen (center)
3. On the _factors list page_ add some title left called _"Factors"_
4. On the _factors list page_ put the units beside the factor captions (e.g. School's car [km/year])
5. In the _factors detail page_ (when adding, changing) add some description pane.
Provide some strings at least in English: _"Please insert the amount of driven kilometers a year for all the school vehicles"_
6. In the _diagrams section_: please review the browser's print out function in order to get readable PDFs

**Comment by Chris3444** [comment]
1,2,3,4 done

**Comment by Chris3444** [comment]
finished all

**Comment by mwallnoefer** [comment]
Some other todos:
- Add the Erasmus+ logo to the app, possibly also in the left upper corner (see mail by Florian)
- homepage/landing page: add some descriptive introduction about the key functionality of the CO² calculator. Mention also that it has been developed by computer science students of the TFO "Max Valier" (credits).
- homepage/landing page: add the howto pdf (mail by Florian) as a link for further reading

Finally:
- please translate the recently added new strings into German and Italian
